# propagation_model: RothermelAndrews2018
# nn_ros_model_path:
propagation_model: ANNPropagationModel
nn_ros_model_path: /home/ai4geo/Documents/nn_ros_models/nn_abs_256_RothermelAndrews2018/saved_model.ffann
fuel_type: [6, 7]
domain_width: 1000
domain_height: 1000
horizontal_wind: 200.0
vertical_wind: 0.0
nb_steps: 20
step_size: 10
fire_front: [[0, 550], [50, 500], [0, 450]]

spatial_increment: 0.5
perimeter_resolution: 2 # max distance between two nodes
minimal_propagative_front_depth: 5 # resolution of arrival time matrix
min_speed: 0.0
max_speed: 100.0
relax: 1 # takes 0.2 of the new ROS and 0.8 of the old ROS, to set in function of spatial_increment!
propagation_speed_adjustment_factor: 1
burned_map_layer: 
